#! /usr/bin/perl

sub total {
	my @numbers = @_;
	my $sum = 0;
	foreach $number (@numbers) {
		$sum += $number;
	}
	$sum;
}

@fred = qw{ 1 3 5 7 9 };
$fred_total = total(@fred);
print "The total of \@fred is $fred_total.\n";
print "Enter some numbers on separate lines: ";
$user_total = total(<STDIN>);
print "The total of those numbers is $user_total.\n";
