#! /usr/bin/perl

sub average {
	my @array = @_;
	my $k = @_;
	my $sum = 0;
	foreach $number (@array) {
		$sum += $number;
	}
	$sum / $k;
}

sub above_average {
	my @array = @_;
	my $average = &average(@array);
	my @result = ();
	foreach $number (@array) {
		if ($number > $average) {
			push @result, $number;
		}
	}
	@result;
}

@fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
@barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
